languageCode = "en-us"
title = "souplab"
theme = "dimension"
baseURL = "http://example.org/"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "souplab"
  description = '仮想的な研究施設'
  logo = "fa-diamond"
  copyright = "souppower"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/souppower"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/souppower"